### PR TITLE
Add i18n support

### PR DESCRIPTION
**Pull request by haukot**

### CODE REVIEW

**Comment by Dreamersoul** [comment]
Thanks for the PR LGTM, can you add an example to the readme file?

**Comment by haukot** [comment]
@Dreamersoul Yep, updated

**Comment by sedubois** [comment]
Now that there is a working test setup, how about adding some tests?

**Comment by Dreamersoul** [comment]
I agree with with @sedubois would you be able to add tests if that's okay?

**Comment by haukot** [comment]
Sure!

**Comment by haukot** [comment]
Hi guys, I updated the PR. 
I've used i18n-tasks for tests, it's automatically checking that all locales are present and used.

**Comment by Dreamersoul** [comment]
sorry for taking too long to release this, got a bit preoccupied. 
Publishing the gem now 🎉

**Pull request merged**
