### PR TITLE
Adds option to support direct uploads

### PR DESCRIPTION
**Pull request by cerdiogenes**

### CODE REVIEW

**Comment by cerdiogenes** [comment]
Thanks for the reminder @Dreamersoul, just updated the PR.

**Comment by Dreamersoul** [comment]
awesome thank you so much! amazing work

**Comment by sedubois** [comment]
When trying this direct upload option, I get `ActionController::InvalidAuthenticityToken`. It seems some other config related to authenticity token is still needed, would you know more about that? Could it be handled directly by administrate-field-active_storage?

**Comment by Dreamersoul** [comment]
From what I know, the config doesn't need authentication, are you following the readme file?

**Comment by sedubois** [comment]
©dreamersoul I seemed to encounter this issue:
https://stackoverflow.com/questions/54679995/ror-invalidauthenticitytoken-with-active-storage-direct-upload/54680623#54680623

For now I just disabled the direct upload.

**Pull request merged**
