### PR TITLE
Update test app and add example test

### PR DESCRIPTION
**Pull request by sedubois**
See commit messages for details.

After merging this we can 
- add more tests
- enable Rubocop, Dependabot...

### CODE REVIEW

**Comment by Dreamersoul** [comment]
First of all thank you for the amazing undertaking for working on this PR. I am loving what I see. I am assuming you're not done with the PR yet.
If you need help with this I am available :+1:

**Comment by sedubois** [comment]
@Dreamersoul could you give your opinion on whether the test app should be in its own directory as in this PR, or merged into the project root?
- A sub-directory allows to better separate test files from the gem's own code, but might make config a bit more difficult (e.g. for running tests in an IDE, deploying app on Heroku, need to manage 2 Gemfiles, ...).
- Merging test app into root provides the most straightforward config, but the separation between the gem's code and the test code is less clear. In particular the root folder looks more cluttered.

I had a look at some of administrate's repo history and I can see they had some challenges when deploying to Heroku. I initially also had issues running the tests in my IntelliJ IDEA but that seems to work now. In the gem I [made](https://github.com/sedubois/mobility-actiontext) recently I currently opted for the second approach but I'm not yet sure it's the best approach and might try using sub-directory like here again.

Also I think I was a bit heavy-handed when generating the test app, I should probably have used --skip-webpacker. I'll try to clean that up.

**Comment by Dreamersoul** [comment]
At first I was confused into why the test project was a subdirectory but after reading your comment I have to agree that the approach with the subdirectory looks better and we can always refactor it later if it breaks down haha.
So yeah subdirectory for now and then we can reevaluate it when we need to

**Comment by sedubois** [comment]
@Dreamersoul it looks okay to me now. At least the tests run on my machine. How to make the GitHub tests show up here? Maybe it only works after merge?

**Comment by Dreamersoul** [comment]
Yeah I think so too, I can merge it when you think it's ready. Should we install administrate and the gem in the test app?

**Comment by sedubois** [comment]
@Dreamersoul I've added a basic test with `administrate-field-active_storage`.

**Comment by sedubois** [comment]
@Dreamersoul the CI test results are visible here and are green:

https://github.com/sedubois/administrate-field-active_storage/actions

**Comment by Dreamersoul** [comment]
Perfect! I can leave this open to add more test cases or I can merge and people slowly add test cases if that suits you! 

Amazing work @sedubois thanks for this great pull request

**Comment by sedubois** [comment]
Sure @Dreamersoul, I suggest to merge asap and tests can progressively be added in other PRs 👍

**Comment by Dreamersoul** [comment]
LGTM :+1:

**Pull request merged**
